### ISSUE TITLE
Platform UI

### ISSUE THREAD

**Issue by vexy** [vexy/simple_voting#4]
Frontend (platform) should allow following features:

- [x] simple home/registration page (#21)
- [x] connect wallet (#6)
- [x] browse all polls (#12)
- [x] add new poll (#7)
- [x] vote on existing poll options (#8)
